Sprint 7 issue #71 add validation in agregar contactos form
BrightCoders-Institute/s8pf-s8a1final-project-team4 pull request #82
Opened 2024-04-13 05:40 UTC by ToshioRonin

# Description

In this branch, the validation of the account number is performed at the moment of adding a contact, first validating if it is already registered in the Firebase database

2024-04-13 14:53 UTC, roobbs approved these changes

2024-04-15 15:50 UTC, Antonio3veces3 reviewed
Resolve ALL conflicts before merge

2024-04-15 23:37 UTC, RicardoRam781 requested changes
resolve conflicts pls

2024-04-15 23:38 UTC, RicardoRam781 approved these changes
resolve confilcts

2024-04-20 00:51 UTC, closed without merging